name: advanced-security/python-lint-code-scanning-action@v1
on: push
jobs: 
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Pylint
        run: pylint main.py
